### ISSUE TITLE
Issues that request Mod support

### ISSUE THREAD

**Issue by vfyjxf** [vfyjxf/NotEnoughEnergistics#1]
If you want Mod support, say it here

**Comment by Coloryr** [comment]
```
java.lang.ClassCastException: appeng.container.implementations.ContainerWirelessPatternTerminal cannot be cast to appeng.container.implementations.ContainerPatternTerm
    at com.github.vfyjxf.nee.client.GuiEventHandler.onDrawScreen(GuiEventHandler.java:163)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3494_GuiEventHandler_onDrawScreen_Post.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:397)
    at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.optifine.reflect.Reflector.callVoid(Reflector.java:669)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1462)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:6114)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

AE2 Unofficial Extended Life
