### ISSUE TITLE
Incompatibility with newer ptae2 versions

### ISSUE THREAD

**Issue by Srdjan-V** [vfyjxf/NotEnoughEnergistics#32]
The pattern terminal is no longer functioning, this is the [commit](https://github.com/PrototypeTrousers/Applied-Energistics-2/commit/b443f1ce5708ad075c2e31f6127a07f029a3fdb4) that introduced this Incompatibility

Log:
```
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: appeng.container.implementations.ContainerPatternTerm.getPatternTerminal()Lappeng/parts/reporting/PartPatternTerminal;
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NoSuchMethodError: appeng.container.implementations.ContainerPatternTerm.getPatternTerminal()Lappeng/parts/reporting/PartPatternTerminal;
    at com.github.vfyjxf.nee.network.packet.PacketRecipeTransfer.lambda$onMessage$0(PacketRecipeTransfer.java:84)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 5 more
```

AE2 version: v0.54.11

NEE version: v1.2.4

**Comment by vfyjxf** [comment]
fix by #33.
