### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Ex5261** [vfyjxf/NotEnoughEnergistics#40]
appliedenergistics2-rv6-stable-7-extended_life-v0.55.6b版本与NotEnoughEnergistics-1.12.2-2.0.3版本有个bug
appliedenergistics2非官方延续版的无线样板终端打开时会使游戏崩溃

java.lang.ClassCastException: appeng.container.implementations.ContainerWirelessPatternTerminal cannot be cast to appeng.container.implementations.ContainerPatternTerm
    at com.github.vfyjxf.nee.client.GuiEventHandler.onDrawScreen(GuiEventHandler.java:163)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3413_GuiEventHandler_onDrawScreen_Post.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:397)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:4114)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Ex5261** [comment]
说实话这有点像是Applied energistics2非官方延续版的bug(可能吧)
只是不知道为什么玩GTNH时每次出问题都有NotEnoughEnergistics的事(??? 1.7.10)

**Comment by vfyjxf** [comment]
算nee的，1.7.10是因为那边他们正在大改动，gtnh那边主要也不是我负责了

**Comment by Ex5261** [comment]
所以是什么问题,什么时候有空修复

**Comment by Ex5261** [comment]
1.7.10我只是问问

**Comment by vfyjxf** [comment]
> 所以是什么问题,什么时候有空修复

下周日吧，现在在学校没办法。

**Comment by Coloryr** [comment]
能修吗。我想修都不知道该改那个分支。

**Comment by vfyjxf** [comment]
> 能修吗。我想修都不知道该改那个分支。

可以，但是我现在腾不出手来，问题代码是[这行](https://github.com/vfyjxf/NotEnoughEnergistics/blob/1.12.2-rework/src/main/java/com/github/vfyjxf/nee/client/GuiEventHandler.java#L163)，pae2往GuiPatternTerm塞了个不同的Container。

**Comment by Coloryr** [comment]
FG2下不到了
换FG3就构建不出来

**Comment by Coloryr** [comment]
丢了好多方法

**Comment by Coloryr** [comment]
![image](https://user-images.githubusercontent.com/26276037/231629437-6332bcdb-4d53-4461-b814-c58331617551.png)
修好了
